integer LINK_COMMAND_REPORT_VERSION = 27382;
integer LINK_COMMAND_CONFIGURE_SERVER = 27383;
integer LINK_COMMAND_CONFIGURE_SCANNER = 27384;

string SCRIPT_SCANNER = "scanner";
string SCRIPT_TRANSMITTER = "transmitter";

string TRANSMITTER_CONFIG_PRODUCTION = "production";
string TRANSMITTER_CONFIG_DEVELOPMENT = "develop";

string SCANNER_CONFIG_PARCEL = "parcel";
string SCANNER_CONFIG_OWNED = "owned";
string SCANNER_CONFIG_REGION = "region";
